In [90]:
from tensorflow.keras.models import load_model
import pickle 
import pandas as pd
import tensorflow as tf

In [91]:
with open('label_encoder.pkl', 'rb') as file:
    label = pickle.load(file)

In [92]:
with open('onehot_encoder.pkl', 'rb') as file:
    oht = pickle.load(file)

In [93]:
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [94]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [95]:
user={'Pclass': 1, 'Sex': 'male', 'SibSp': 1, 'Parch': 0, 'Fare': 52, 'Embarked': 'Queenstown'}

In [96]:
user=pd.DataFrame([user])

In [97]:
user

   Pclass   Sex  SibSp  Parch  Fare    Embarked
0       1  male      1      0    52  Queenstown

In [98]:
user['Sex']=label.transform(user['Sex'])

In [99]:
embarked=oht.transform(user[['Embarked']])

In [100]:
embarked=pd.DataFrame(embarked, columns=oht.get_feature_names_out())

In [101]:
user=pd.concat([user, embarked], axis=1).drop('Embarked', axis=1)

In [102]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1,1,1,0,52,0.0,1.0,0.0

In [103]:
user[['Pclass','SibSp','Parch','Fare']]=scaler.transform(user[['Pclass','SibSp','Parch','Fare']])

In [104]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,1,0.442462,-0.469267,0.981368,0.0,1.0,0.0

In [105]:
y=model.predict(user)

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000016EEFFF8540> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000016EEFFF8540> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 612ms/step

In [106]:
y

array([[0.320639]], dtype=float32)