In [70]:
import pandas as pd

In [71]:
df=pd.read_csv('huge_1M_titanic.csv')

In [72]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
467579,468889,0,3,"Name468889, Mr. Surname468889",male,30.0,0,0,A/4. 34244,11.829573,NaN,Q
740748,742058,0,3,"Name742058, Mr. Surname742058",male,27.0,0,0,17453,19.559813,C83,S
653076,654386,1,1,"Name654386, Mr. Surname654386",male,32.0,1,0,SOTON/O.Q. 392087,65.082365,D26,C
686931,688241,1,1,"Name688241, Mr. Surname688241",male,29.0,0,0,19988,56.527451,NaN,S
771186,772496,0,2,"Name772496, Mr. Surname772496",male,27.0,0,0,28665,7.938320,NaN,S

In [73]:
df.shape

(1000000, 12)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  object
 4   Sex          1000000 non-null  object
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  object
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   object
 11  Embarked     997760 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 91.6+ MB

In [75]:
df.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

In [76]:
df=df.drop(columns=['PassengerId','Name','Age','Ticket','Cabin'])

In [77]:
df.sample(5)

        Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
768736         1       3    male      0      0   2.006089        S
362717         1       2  female      1      0  30.021233        S
747995         1       1    male      1      0  67.906513        C
57316          0       3    male      0      0   7.448253        S
246756         1       2  female      0      0  22.562172        S

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Survived  1000000 non-null  int64
 1   Pclass    1000000 non-null  int64
 2   Sex       1000000 non-null  object
 3   SibSp     1000000 non-null  int64
 4   Parch     1000000 non-null  int64
 5   Fare      1000000 non-null  float64
 6   Embarked  997760 non-null   object
dtypes: float64(1), int64(4), object(2)
memory usage: 53.4+ MB

In [79]:
df['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [80]:
df['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [81]:
df['Embarked']=df['Embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queenstown'})

In [82]:
df.dropna(subset=['Embarked'], inplace=True)

In [83]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [84]:
df.shape

(997760, 7)

In [85]:
df['Fare']=df['Fare'].astype('int8')

In [86]:
df.head(5)

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76    Cherbourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12    Cherbourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4    Cherbourg

# FEATURE ENCODING

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
label = LabelEncoder()

In [89]:
df['Sex']=label.fit_transform(df['Sex'])

In [90]:
from sklearn.preprocessing import OneHotEncoder

In [91]:
oht=OneHotEncoder(sparse_output=False)

In [92]:
Embarked=oht.fit_transform(df[['Embarked']])

In [93]:
Embarked=pd.DataFrame(Embarked, columns=oht.get_feature_names_out())

In [94]:
Embarked

        Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                      1.0                  0.0                   0.0
1                      0.0                  0.0                   1.0
2                      1.0                  0.0                   0.0
3                      0.0                  0.0                   1.0
4                      1.0                  0.0                   0.0
...                    ...                  ...                   ...
997755                 0.0                  0.0                   1.0
997756                 0.0                  0.0                   1.0
997757                 0.0                  0.0                   1.0
997758                 0.0                  0.0                   1.0
997759                 0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [95]:
df=pd.concat([df.drop(columns=['Embarked']), Embarked], axis=1)

In [96]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

FEATURE SCALING

In [97]:
from sklearn.preprocessing import StandardScaler

In [98]:
scale=StandardScaler()

In [99]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cherbourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='object')

In [100]:
num_cols=['Pclass','SibSp','Parch','Fare']

In [101]:
df[num_cols]=scale.fit_transform(df[num_cols])

In [102]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [103]:
import pickle

In [104]:
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label, file)

In [105]:
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(oht, file)

In [106]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scale, file)

# TRAIN TEST SPLIT

In [107]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [138]:
X.isnull().sum()

Pclass                  2234
Sex                     2234
SibSp                   2234
Parch                   2234
Fare                    2234
Embarked_Cherbourg      2234
Embarked_Queenstown     2234
Embarked_Southampton    2234
dtype: int64

In [141]:
X=X.dropna()

In [145]:
y.isnull().sum()

np.int64(0)

In [144]:
y=y.dropna()

In [142]:
df.isnull().sum()

Survived                0
Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Cherbourg      0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [146]:
from sklearn.model_selection import train_test_split

In [149]:
y = y.loc[X.index]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20, random_state=42)

In [150]:
X_train,X_val,y_train,y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# MODEL BUILDING

In [151]:
import tensorflow

In [152]:
X_train.shape[1]

8

In [153]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [154]:
model=Sequential([Dense(128,input_shape=(X_train.shape[1],), activation='relu'),
                  Dense(64, activation='relu'),
                  Dense(32, activation='relu'),
                Dense(1, activation='sigmoid')])

c:\Users\harsh\OneDrive\Desktop\Gen AI\Deep Learning\ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [155]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,521 (45.00 KB)

 Trainable params: 11,521 (45.00 KB)

 Non-trainable params: 0 (0.00 B)

In [156]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [157]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [158]:
EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [160]:
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10)

Epoch 1/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 226s 9ms/step - accuracy: 0.8499 - loss: 0.3385 - val_accuracy: 0.8419 - val_loss: 0.3436
Epoch 2/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 263s 9ms/step - accuracy: 0.8501 - loss: 0.3376 - val_accuracy: 0.8512 - val_loss: 0.3338
Epoch 3/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 189s 8ms/step - accuracy: 0.8503 - loss: 0.3371 - val_accuracy: 0.8544 - val_loss: 0.3307
Epoch 4/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 108s 4ms/step - accuracy: 0.8509 - loss: 0.3361 - val_accuracy: 0.8523 - val_loss: 0.3378
Epoch 5/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 112s 4ms/step - accuracy: 0.8518 - loss: 0.3353 - val_accuracy: 0.8517 - val_loss: 0.3314
Epoch 6/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 170s 7ms/step - accuracy: 0.8517 - loss: 0.3355 - val_accuracy: 0.8549 - val_loss: 0.3287
Epoch 7/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 183s 7ms/step - accuracy: 0.8523 - loss: 0.3347 - val_accuracy: 0.8547 - val_loss: 0.3288
Epoch 8/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 146s 6ms/step - accuracy: 0.8523 - loss: 0.3347 - val_accuracy: 0.8552 - val_loss: 0.3320
Epoch 9/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 228s 9ms/step - accuracy: 0.8522 - loss: 0.3347 - val_accuracy: 0.8541 - val_loss: 0.3325
Epoch 10/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 228s 9ms/step - accuracy: 0.8523 - loss: 0.3351 - val_accuracy: 0.8542 - val_loss: 0.3279

In [161]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.